packages:
  - "apps/*"
  - "packages/*"
catalogs:
  default:
    typescript: "^5.8.3"
    zod: "^4.3.6"
    uuid: "^13.0.0"
    "@types/node": "^20.11.17"
    "@types/uuid": "^11.0.0"
    hono: "^4.11.9"
    "@hono/node-server": "^1.19.9"
    "@hono/standard-validator": "^0.2.2"
    "@hono/zod-openapi": "^1.2.2"
    "@scalar/hono-api-reference": "^0.9.41"
    hono-openapi: "^1.2.0"
    tsx: "^4.7.1"
    react: "^19.2.0"
    react-dom: "^19.2.0"
    "@hookform/resolvers": "^5.2.2"
    "@tailwindcss/vite": "^4.1.18"
    "@tanstack/react-query": "^5.90.21"
    class-variance-authority: "^0.7.1"
    clsx: "^2.1.1"
    lucide-react: "^0.564.0"
    radix-ui: "^1.4.3"
    react-hook-form: "^7.71.1"
    sonner: "^2.0.7"
    tailwind-merge: "^3.4.1"
    tailwindcss: "^4.1.18"
    vercel: "^50.19.1"
    zustand: "^5.0.11"
    "@eslint/js": "^9.39.1"
    "@types/react": "^19.2.7"
    "@types/react-dom": "^19.2.3"
    "@vitejs/plugin-react": "^5.1.1"
    eslint: "^9.39.1"
    eslint-plugin-react-hooks: "^7.0.1"
    eslint-plugin-react-refresh: "^0.4.20"
    globals: "^16.5.0"
    shadcn: "^3.8.4"
    tw-animate-css: "^1.4.0"
    vite: "^7.3.1"
    typescript-eslint: "^8.48.0"